### ISSUE TITLE
Change the source of top user agents to a more reliable website

### ISSUE THREAD

**Issue by Goplr** [Kikobeats/top-user-agents#30]
The current source of top user agents, [techblog.willhouse.com](https://techblog.willshouse.com), has been down since the start of December 2023. It returns a "ERROR 404 - PAGE NOT FOUND" message whenever I try to access it. This website has been unstable for a long time and I doubt it will be fixed anytime soon.

I suggest changing the source of top user agents to a more reliable and up-to-date website, such as [Useragents.me](https://www.useragents.me/). This website provides a self-updating list of the latest and most common user agents for all device types, operating systems, and browsers. It also has an API that can be used to get the user agent data in JSON or TSV format.

This change would improve the quality and accuracy of the top user agents data and make the project more useful for web scrapers, developers, and researchers.

**Comment by fenopa** [comment]
https://github.com/Kikobeats/top-user-agents/issues/28

**Comment by fenopa** [comment]
Useragents.me doesn't look so accurate. It says Mac OS X, Safari is the "Most Common Desktop Useragent" with 31.5 share and Windows Chrome is second with 17.34 share. That's very unlikely.

**Comment by kevinvanrijn** [comment]
There are several oddities with [useragents.me](https://www.useragents.me/). Specifically the "Most Common Desktop Useragents" list.

1. (Already mentioned above) Safari is severely overrepresented. In previous data here it almost always appeared after each combination of Windows/Mac/Linux + Chrome/Firefox. And Windows + Chrome was always the undefeated king.
2. The same for Mac OS being overrepresented compared to Windows.
3. For some reason Firefox isn't even recognized with it being listed as Other like it never came up when the site was written when it should be more popular than Safari even on Mac OS.
4. The list has weird gaps in it. Firefox again stands out the most with `Firefox/117` & `Firefox/115` somehow still making the list when `Firefox/119` (latest -1) doesn't.

Something is going wrong in that list. [useragents.me](https://www.useragents.me/) is either listing traffic over way too short of a timespan, doesn't get enough traffic, or is receiving an abnormal amount of traffic from somewhere. Most likely at least 2 of these.

Even stranger is that [useragents.me/api](https://www.useragents.me/api) doesn't suffer from these issues but hasn't been updated since the start of this year. It is severely outdated but does correctly put Windows before Mac OS and both Chrome & Firefox before Safari.

You could get a guess out of [useragents.me](https://www.useragents.me/)'s data by limiting it to only the first couple of UAs and then dragging any Safari or Mac OS results to the bottom but that wouldn't be good for anything beyond getting the latest version numbers.

**Comment by Kikobeats** [comment]
My websites has more than 100M requests per month. I'm building a simple redis counter for user agents that can return N items from head, so you can get top10, top100 or top1000.

will be published soon as major version of this library 🙂
